[package]
name = "rrmi"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
fastwebsockets = "0.10.0"
serde = {version= "1.0.228", features=["derive"]}
serde_cbor = "0.11.2"
thiserror = "2.0.18"
tokio = {version = "1.49.0", features = ["net"]}
