[package]
name = "rrmi"
version = "0.1.0"
edition = "2024"

[dependencies]
dns-lookup = "3.0.1"
fastwebsockets = "0.10.0"
local-ip-address = "0.6.10"
serde = {version= "1.0.228", features=["derive"]}
serde_cbor = "0.11.2"
thiserror = "2.0.18"
threadpool = "1.8.1"
